# Generated by Django 5.0.4 on 2024-04-27 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.FileField(upload_to='gt_files'),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_day', models.DateTimeField(default='')),
                ('state', models.BooleanField(default=False)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_team', to='teams.team')),
                ('matchweek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_fixture', to='teams.fixture')),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_team', to='teams.team')),
            ],
        ),
    ]
