# Generated by Django 5.0.4 on 2024-04-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_fixture_alter_team_image_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_day',
            field=models.DateTimeField(null=True),
        ),
    ]
